---
name: Release

on:
  push:
    tags:
      - "*"

jobs:
  release:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: clone repository
        uses: actions/checkout@v4

      - name: Install mise
        uses: jdx/mise-action@v2
        with:
          install: true
          cache: true

      - name: install client deps
        working-directory: ./client
        run: deno install

      - name: build client
        working-directory: ./client
        run: deno task build

      - name: remove client deps
        run: deno clean

      - name: install deps
        run: deno install --entrypoint --unstable-npm-lazy-caching src/main.ts

      - name: build
        run: ./scripts/build.ts

      - name: release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "./.bin/denotag-*.tar.gz,./.bin/denotag-*.zip,./.bin/denotag-*.sha256"
